### ISSUE TITLE
Setting default schema same as database default schema results in incorrect comparison

### ISSUE THREAD

**Issue by adamjez** [JonPSmith/EfSchemaCompare#5]
Hi,

I ran into minor bug in `EfCore.SchemaCompare` 5.1.4 version (latest).

Setting default schema in `DbContext` to same value as default database schema (most likely `dbo`) results in incorrect comparison. This then most probably results in errors like `NOT IN DATABASE: Entity 'Author', table name. Expected = dbo.Authors`

Reproducing it is easy.  Add `modelBuilder.HasDefaultSchema("dbo");` to `BookContext`  and most unit tests will fail.

The main issue is in methods that generates table names:
* `FormSchemaTableFromModel` - generates `dbo.Author` because we had explicitly specified `dbo` schema
* `FormSchemaTableFromDatabase` - generates `Author` because `table.Schema == defaultSchema`

**Comment by JonPSmith** [comment]
Interesting. The handling of the default schema is difficult because the `DbContext.Model` returns `null` fro default, but the scaffold returns the actual schema name in the database. Your example must cause a problem.

I'll leave this issue open, but a) I'm busy and b) its a minor bug so I won't look at it at the moment.

**Comment by JonPSmith** [comment]
Hi @adamjez,

I have decided to not update this as the code is quite complex and the bug is small. Sorry about that but I have about 5 libraries that I need to update to NET6 so I have enough to do.
